# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &ejg_getsuga A2A3CA505C4E424A8616DB04E5F750C199A99023
  - &ejg_void 35D469C06B616D2BCF1980A33B8BFDA530FDAE77
  - &server_void age1ws2gphsp0qwzpw24j3wkmtgfz7e2cfhmkzpu8xkruyzrxjd334yshj2843
  - &server_getsuga age148zsrhvarvtzlyhlt4yayrf9705jvpsntgjk6r5cvvg0c0qeu9rqf20wpd

creation_rules:
  - path_regex: secrets/getsuga/.*
    key_groups:
    - age:
      - *server_getsuga
      pgp:
      - *ejg_getsuga
      - *ejg_void
  - path_regex: secrets/void/.*
    key_groups:
    - age:
      - *server_void
      pgp:
      - *ejg_getsuga
      - *ejg_void
  - path_regex: secrets/.*
    key_groups:
    - age:
      - *server_void
      - *server_getsuga
      pgp:
      - *ejg_getsuga
      - *ejg_void
