{
  imports = [
    ./allowed-unfree.nix
    ./waybar.nix
    ./lib.nix
    ./gtk.nix
    ./lan.nix
    ./yt-dlp.nix
    ./qutebrowser.nix
    ./packages.nix
    ./cursor.nix
    ./helix.nix
    ./nixos-rebuild.nix
    ./wg.nix
    ./wrap.nix
    ./themes.nix
    ./greetd.nix
  ];
}
