name: "Make WSL"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build WSL
        run: sudo nix run .#mk-weasel-tarball
      - name: Save to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nixos-wsl.tar.gz

